pod 'AFNetworking', '~> 3.0.3'
pod 'SDWebImage', '~> 3.7.3'
pod 'MagicalRecord', '~> 2.3.0'
pod 'JSONModel', '~> 1.1.2'
pod 'ViewUtils', '~> 1.1.2'
pod 'IQKeyboardManager', '~> 3.3.4'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SVProgressHUD-0.8.1', '~> 0.8'







